language: java

jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "UEV7IXcOH/+mMrIMWjv+epoWguxW0sCyDUmQsSOw9tafNGzCgusxPKyPRqiYn1LT5LdIDSHXq9GwU5j2vf73/muflgFlNUcGTUfQGJZobClb1CfWYvhTbqwsIcdQkK8t+HE6zMr+W/ZB150sOij017ZscLU125+kT3CjWXwG6W8="

addons:
  coverity_scan:
    project:
      name: "McPringle/sportchef"
      description: "Build submitted via Travis CI"
    notification_email: marcus@fihlon.ch
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew compileJava compileTestJava"
    branch_pattern: coverity_scan

after_success:
  - ./gradlew jacocoTestReport coveralls
