server:
  rootPath: '/api/*'

database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:./sportchefdb
  properties:
    charSet: UTF-8
  validationQuery: "/* Health Check */ SELECT 1"

logging:
  level: ALL
  appenders:
    - type: console
      threshold: INFO
      target: stdout
    - type: file
      currentLogFilename: ./logs/sportchef-server.log
      archivedLogFilenamePattern: ./logs/sportchef-server-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
